### ISSUE TITLE
Pergunta: Poderia verificar o view-model antes?

### ISSUE THREAD

**Issue by amadeu01** [pietrocaselani/UnitTestExamples#1]
https://github.com/pietrocaselani/UnitTestExamples/blob/1cd41935df4d914bc6bb3952a91c30a8c129143e/TestsExample/MoviesViewController.swift#L12-L14

Você não poderia testar se o view-model existe antes de carregar a view no janela?
Poderia fazer isso no `viewWillLoad`?

**Comment by pietrocaselani** [comment]
Neste caso, eu prefiro criar um XIB e implementar um "custom init" com o que eu preciso injetar no ViewController.
